# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
#  - 5.3
  - 5.4
#  - 5.5
#  - hhvm

env:
  - MAGE=1.9.1.0
#  - MAGE=1.8.1.0
#  - MAGE=1.7.0.2
#  - MAGE=1.6.2.0
#  - MAGE=1.5.1.0

before_install:
  - mkdir test/
  - composer self-update

install:
  - composer install --dev
#  - curl https://gordonlesti.com/"$MAGE".tar.gz | tar xz
  - bin/mage-ci install magento/$MAGE $MAGE test`echo $MAGE|sed -e 's/[\.]//g'` -c -t -r http://mage-ci.magedev.ru
  - cd magento/$MAGE
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - cd ..

before_script:
#http://www.magentocommerce.com/downloads/assets/1.9.1.0/magento-1.9.1.0.tar.gz
  - composer selfupdate
  - mkdir -p build/logs
  - composer update --ignore-platform-reqs
  - hhvm $(which composer) update
#  - cd magento
#  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
#  - cd ..

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - phpcs --standard=Zend -n app/
  - phpmd app/ text codesize,design,unusedcode
  - phpcpd app/
  - cd magento && php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml && cd ..

after_script:
  - coveralls

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
      - "builds@magedev.ru"
