# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - MAGE=magento-1-9-1-0
  - MAGE=magento-1-9-0-1
  - MAGE=magento-1-8-1-0
  - MAGE=magento-1-7-0-2
  - MAGE=magento-1-6-2-0
  - MAGE=magento-1-5-1-0
before_install:
  - mkdir test/
  - composer install --dev

before_script:
http://www.magentocommerce.com/downloads/assets/1.9.1.0/magento-1.9.1.0.tar.gz
  - composer selfupdate
  - composer update
  - bin/ci.sh
  - cd $TRAVIS_BUILD_DIR/public

before_script:
  - CURR_DIR=$(pwd)
  - mkdir -p build/logs
  - mysql -e 'create database `magento`;'
  - mysql -utravis magento < magento/var/magento.sql
  - mysql -e 'create database `magento_test`;'
  - mysql -utravis magento_test < magento/var/magento_test.sql
  - cd magento
  - ./modman link ./../../Lesti_Fpc
  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd ..

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - php vendor/bin/phpcs --standard=Zend -n app/
  - php vendor/bin/phpmd app/ text codesize,design,unusedcode
  - php vendor/bin/phpcpd app/
  - cd magento && php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml && cd ..

after_script:
  - php vendor/bin/coveralls

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
      - "builds@magedev.ru"
  #irc: "chat.freenode.net#magetest"