# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
sudo: false

# list any PHP version you want to test against
php:
#  - 5.3
  - 5.4
#  - 5.5
#  - hhvm


env:
  - MAGE=1.9.1.0
#  - MAGE=1.8.1.0
#  - MAGE=1.7.0.2
#  - MAGE=1.6.2.0
#  - MAGE=1.5.1.0

before_install:
  - mkdir test/
  - composer self-update

install:
  - composer selfupdate
  - composer install
  - bin/mage-ci install magento/"$MAGE" $MAGE test`echo $MAGE|sed -e 's/[\.]//g'` -c -t -r http://mage-ci.magedev.ru
  - bash < <(wget -q --no-check-certificate -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - cd magento/"$MAGE"
  - modman init

before_script:
  - composer update --ignore-platform-reqs
  - mkdir -p build/logs
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - hhvm $(which composer) update
#  - cd magento
#  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
#  - cd ..

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - phpcs --standard=Zend -n app/
  - phpmd app/ text codesize,design,unusedcode
  - phpcpd app/
  - cd magento && php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml && cd ..

after_script:
  - coveralls

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
      - "builds@magedev.ru"
